Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def get_statistic(adjacencies, return_latents=False):
    """
    Get the operator norm of the difference of two matrices.
    """
    latents_est = omni.fit_transform(adjacencies)
    X, Y = latents_est[0], latents_est[1]
    y = np.linalg.norm(X - Y, ord=2)
    if return_latents:
        return y, X
    else:
        return y

y, Xhat = get_statistic(networks[0:2], return_latents=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1935/3595308081.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m         [0;32mreturn[0m [0my[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;34m[0m[0m
[0;32m---> 13[0;31m [0my[0m[0;34m,[0m [0mXhat[0m [0;34m=[0m [0mget_statistic[0m[0;34m([0m[0mnetworks[0m[0;34m[[0m[0;36m0[0m[0;34m:[0m[0;36m2[0m[0;34m][0m[0;34m,[0m [0mreturn_latents[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_1935/3595308081.py[0m in [0;36mget_statistic[0;34m(adjacencies, return_latents)[0m
[1;32m      3[0m     [0mGet[0m [0mthe[0m [0moperator[0m [0mnorm[0m [0mof[0m [0mthe[0m [0mdifference[0m [0mof[0m [0mtwo[0m [0mmatrices[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     """
[0;32m----> 5[0;31m     [0mlatents_est[0m [0;34m=[0m [0momni[0m[0;34m.[0m[0mfit_transform[0m[0;34m([0m[0madjacencies[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m     [0mX[0m[0;34m,[0m [0mY[0m [0;34m=[0m [0mlatents_est[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mlatents_est[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m     [0my[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinalg[0m[0;34m.[0m[0mnorm[0m[0;34m([0m[0mX[0m [0;34m-[0m [0mY[0m[0;34m,[0m [0mord[0m[0;34m=[0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'omni' is not defined
NameError: name 'omni' is not defined

