Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pkg.stats import stochastic_block_test

stat, pvalue, misc = stochastic_block_test(
    Aday, Anight, labels1=z, labels2=z, method="fisher", correct_method="holm", combine_method="tippett"
)
print("p-value: {:.3f}".format(pvalue))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[11], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpkg[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstats[39;00m [38;5;28;01mimport[39;00m stochastic_block_test
[0;32m----> 3[0m stat, pvalue, misc [38;5;241m=[39m [43mstochastic_block_test[49m[43m([49m
[1;32m      4[0m [43m    [49m[43mAday[49m[43m,[49m[43m [49m[43mAnight[49m[43m,[49m[43m [49m[43mlabels1[49m[38;5;241;43m=[39;49m[43mz[49m[43m,[49m[43m [49m[43mlabels2[49m[38;5;241;43m=[39;49m[43mz[49m[43m,[49m[43m [49m[43mmethod[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mfisher[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mcorrect_method[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mholm[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mcombine_method[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mtippett[39;49m[38;5;124;43m"[39;49m
[1;32m      5[0m [43m)[49m
[1;32m      6[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mp-value: [39m[38;5;132;01m{:.3f}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(pvalue))

[0;31mTypeError[0m: stochastic_block_test() got an unexpected keyword argument 'correct_method'
TypeError: stochastic_block_test() got an unexpected keyword argument 'correct_method'

