Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from graspologic.simulations import rdpg
from graphbook_code import draw_multiplot

n = 100  # the number of nodes in our network

# design the latent position matrix X according to 
# the rules we laid out previously
X = np.zeros((n,2))
for i in range(0, n):
    X[i,:] = [(n - i)/n, i/n]

from graspologic.simulations import rdpg
from graphbook_code import draw_multiplot

A = rdpg(X, directed=False, loops=False)
draw_multiplot(A, title="RDPG Simulation");
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgraspologic[39;00m[38;5;21;01m.[39;00m[38;5;21;01msimulations[39;00m [38;5;28;01mimport[39;00m rdpg
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgraphbook_code[39;00m [38;5;28;01mimport[39;00m draw_multiplot
[1;32m      5[0m n [38;5;241m=[39m [38;5;241m100[39m  [38;5;66;03m# the number of nodes in our network[39;00m
[1;32m      7[0m [38;5;66;03m# design the latent position matrix X according to [39;00m
[1;32m      8[0m [38;5;66;03m# the rules we laid out previously[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/graphbook_code/__init__.py:31[0m, in [0;36m<module>[0;34m[0m
[1;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01msiem[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     30[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01msbm[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m---> 31[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mier[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/graphbook_code/ier.py:15[0m, in [0;36m<module>[0;34m[0m
[1;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstats[39;00m [38;5;28;01mimport[39;00m bernoulli
[1;32m     14[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Any, Callable, Optional, Union
[0;32m---> 15[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgraspologic[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtypes[39;00m [38;5;28;01mimport[39;00m Dict, List, Tuple
[1;32m     17[0m [38;5;28;01mdef[39;00m [38;5;21mier[39m(
[1;32m     18[0m     P: np[38;5;241m.[39mndarray,
[1;32m     19[0m     rescale: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[0;32m   (...)[0m
[1;32m     23[0m     wtargs: Optional[Dict[[38;5;28mstr[39m, Any]] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m     24[0m ) [38;5;241m-[39m[38;5;241m>[39m np[38;5;241m.[39mndarray:
[1;32m     25[0m     [38;5;124mr[39m[38;5;124;03m"""[39;00m
[1;32m     26[0m [38;5;124;03m    Samples a random graph, given a probability matrix.[39;00m
[1;32m     27[0m [38;5;124;03m    :math:`P = (p_{ij})_{i,j = 1}^n` is the probability matrix, where each entry :math:`p_{ij} \in [0, 1]`[39;00m
[0;32m   (...)[0m
[1;32m     68[0m [38;5;124;03m           [1., 1., 1., 0., 0.]])[39;00m
[1;32m     69[0m [38;5;124;03m    """[39;00m

[0;31mImportError[0m: cannot import name 'Dict' from 'graspologic.types' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/graspologic/types.py)
ImportError: cannot import name 'Dict' from 'graspologic.types' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/graspologic/types.py)

